### ISSUE TITLE
Custom Games

### ISSUE THREAD

**Issue by powerjbn** [theGrue/jeopardy#1]
I know that no one has cared about this project for a while, but its there any easy way to make custom games? This is the best Jeopardy program I have found, but I can't figure out exactly what part of the program I need to modify that would let me make a custom game.

**Comment by theGrue** [comment]
Hey, thanks for the compliment! Custom games would be fun, at one point I thought I might try to make my own to challenge my friends with, but I never got there. 

The quickest and dirtiest way would probably be this:
- Find a game that had all its clues revealed, such as http://localhost:3000/api/games/5302, and open it in your browser.
- Paste it into a text editor of your choice, replace the clues with your own, and save it somewhere.
- Modify the `exports.game` function within api.js to load your JSON file instead of calling out to J! Archive.
- Depending on how you implemented the previous step, point your browser to http://localhost:3000/#/games/mygame or something like that and play your game!

If the API serves up some JSON in a format that the front end understands, it doesn't really matter whether it came from J! Archive or not.

Like I said, that's the quick and dirty, if you come up with something more elegant, feel free to PR!

**Comment by powerjbn** [comment]
Thanks!
